language: c

sudo: required

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

#env:
#  global:
#    - LD_LIBRARY_PATH=/usr/local/lib
#    - LD_RUN_PATH=/usr/local/lib

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install swig python-all-dev python-numpy cython fpc gfortran php-config lua5.2 liblua5.2-dev python3-all-dev python3-numpy ; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install swig ruby python python3 fpc lua && pip install Cython numpy && pip3 install numpy ; fi

#install:
#  - if [ $TRAVIS_OS_NAME == linux ]; then ./travis-deps.sh ; fi

script:
  - autoreconf -fi && ./configure --enable-php --enable-pascal --disable-python --disable-python-numpy && make && make check && make distclean
  - autoreconf -fi && ./configure --disable-all-bindings CFLAGS="-std=c89 -pedantic" && make && make check && make distclean
  - autoreconf -fi && ./configure --enable-python-numpy --enable-python PYTHON=python && make && make check && make distclean
  - autoreconf -fi && ./configure --enable-python-numpy --enable-python PYTHON=python3 && make && make check && make distclean

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - Tom.Schoonjans@me.com
    on_success: never
    on_failure: always

