language: java

env:
  global:
    - FCLAGS="-g -O0"
    - CPPFLAGS="-D_FORTIFY_SOURCE=2"

matrix:
  allow_failures:
    - os: linux
      jdk:
        - openjdk8
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.7
            - gfortran-4.7
      env: CC='gcc-4.7' FC='gfortran-4.7' XRL_PYTHON2='/usr/bin/python' XRL_PYTHON3='/usr/bin/python3'
    - os: linux
      jdk:
        - openjdk8
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - gfortran-4.9
      env: CC='gcc-4.9' FC='gfortran-4.9' XRL_PYTHON2='/usr/bin/python' XRL_PYTHON3='/usr/bin/python3'
  include:
    - os: linux
      jdk:
        - openjdk8
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang
      env: CC='/usr/bin/clang' EXTRA='--disable-fortran2003 --disable-openmp' XRL_PYTHON2='/usr/bin/python' XRL_PYTHON3='/usr/bin/python3'
    - os: linux
      jdk:
        - openjdk8
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.8
            - gfortran-4.8
      env: CC='gcc-4.8' FC='gfortran-4.8' XRL_PYTHON2='/usr/bin/python' XRL_PYTHON3='/usr/bin/python3'
    - os: linux
      jdk:
        - openjdk8
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - gfortran-5
      env: CC='gcc-5' FC='gfortran-5' XRL_PYTHON2='/usr/bin/python' XRL_PYTHON3='/usr/bin/python3'
    - os: linux
      jdk:
        - openjdk8
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - gfortran-6
      env: CC='gcc-6' FC='gfortran-6' XRL_PYTHON2='/usr/bin/python' XRL_PYTHON3='/usr/bin/python3'
    - os: linux
      jdk:
        - openjdk8
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - gfortran-7
      env: CC='gcc-7' FC='gfortran-7' XRL_PYTHON2='/usr/bin/python' XRL_PYTHON3='/usr/bin/python3'
    - os: linux
      jdk:
        - openjdk10
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-8
            - gfortran-8
      env: CC='gcc-8' FC='gfortran-8' XRL_PYTHON2='/usr/bin/python' XRL_PYTHON3='/usr/bin/python3'
    - os: linux
      jdk:
        - openjdk11
      dist: xenial
      sudo: required
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
            - gfortran-9
      env: CC='gcc-9' FC='gfortran-9' XRL_PYTHON2='/usr/bin/python' XRL_PYTHON3='/usr/bin/python3'

before_install:
  - |
    if [ $TRAVIS_OS_NAME == linux ] ; then
      sudo apt-get --yes --force-yes update || exit 1
      sudo apt-get --yes --force-yes install python-all-dev python-numpy python3-all-dev python3-numpy fpc gfortran php-dev lua5.2 liblua5.2-dev || exit 1
      sudo pip install Cython || exit 1
    fi
  - rm -rf $HOME/.phpenv

install:
  - |
    if [ $TRAVIS_OS_NAME == linux ]; then
      wget http://prdownloads.sourceforge.net/swig/swig-4.0.1.tar.gz || exit 1
      tar xfz swig-4.0.1.tar.gz || exit 1
      cd swig-4.0.1 || exit 1
      ./configure || exit 1
      make || exit 1
      sudo make install || exit 1
      cd ..
    fi


script:
  - autoreconf -fi || exit 1
  - ./configure --disable-python --disable-python-numpy --disable-ruby --enable-perl --enable-lua --enable-pascal --enable-java --enable-php --enable-ruby ${MYSHELL} ${EXTRA} || exit 1
  - make || exit 1
  - make check || exit 1
  - make distclean || exit 1
  - ./configure --disable-all-bindings CFLAGS="-std=c89 -pedantic" ${MYSHELL} || exit 1
  - make || exit 1
  - make check || exit 1
  - make distclean || exit 1
  - ./configure --disable-ruby --disable-perl --disable-lua --enable-python-numpy --enable-python PYTHON=${XRL_PYTHON2} ${EXTRA} ${MYSHELL} || exit 1
  - make || exit 1
  - make check || exit 1
  - make distclean || exit 1
  - ./configure --disable-ruby --disable-perl --disable-lua --enable-python-numpy --enable-python PYTHON=${XRL_PYTHON3} ${EXTRA} ${MYSHELL} || exit 1
  - make || exit 1
  - make check || exit 1
  - make distclean || exit 1
  - ./configure --disable-all-bindings --disable-shared --enable-static || exit 1
  - make || exit 1
  - make check || exit 1
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ] ; then
      make distclean || exit 1
      ./configure --disable-all-bindings || exit 1
      make distcheck PYTHON=${XRL_PYTHON2} || exit 1
    fi

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - Tom.Schoonjans@me.com
    on_success: never
    on_failure: always

