[build-system]
requires = ["mesonpep517", "ninja", "Cython", "numpy"]
build-backend = "mesonpep517.buildapi"

dependencies = [
  "numpy"
]

[tool.mesonpep517.metadata]
author = "Tom Schoonjans"
author-email = "Tom.Schoonjans@gmail.com"
summary = "pip-installable xraylib"
home-page = "https://github.com/tschoonj/xraylib"
meson-python-option-name = "python"
meson-options = [
  "-Ddefault_library=static",
  "-Dpython-bindings=enabled",
  "-Dpython-numpy-bindings=enabled"
]